PUBLIC_KEY = File.read(File.expand_path("~/.ssh/id_rsa.pub")).strip
DOCKER_COMPOSE = File.read(File.expand_path("docker-compose.yml")).strip
MASTER_SH = File.read(File.expand_path("master.sh")).strip

# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/xenial64"

  config.vm.provider "virtualbox" do |vb|
    # vb.memory = "4096"
    # vb.cpus = "6"
    vb.memory = "1024"
    vb.cpus = "2"

  end

  # vm2 - swarm worker
  config.vm.define "vm2" do |vm2|
    vm2.vm.network "private_network", ip: "10.0.0.102"
    vm2.vm.hostname = "vm2"

    vm2.vm.provision "shell", inline: <<-SHELL
      apt-get -y update
      apt-get -y upgrade 
      apt-get -y autoremove 
      apt-get install -y vim
      echo "#{PUBLIC_KEY}" >> /home/vagrant/.ssh/authorized_keys

      sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
      curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
      sudo apt-key fingerprint 0EBFCD88
      sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
      sudo apt-get -y update
      sudo apt-get -y install docker-ce
      sudo curl -L https://github.com/docker/compose/releases/download/1.16.1/docker-compose-`uname -s`-` uname -m` -o /usr/local/bin/docker-compose
      sudo chmod +x /usr/local/bin/docker-compose
    SHELL

  end

  # vm3 - swarm worker
  config.vm.define "vm3" do |vm3|
    vm3.vm.network "private_network", ip: "10.0.0.103"
    vm3.vm.hostname = "vm3"

    vm3.vm.provision "shell", inline: <<-SHELL
      apt-get -y update
      apt-get -y upgrade 
      apt-get -y autoremove 
      apt-get install -y vim
      echo "#{PUBLIC_KEY}" >> /home/vagrant/.ssh/authorized_keys

      sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
      curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
      sudo apt-key fingerprint 0EBFCD88
      sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
      sudo apt-get -y update
      sudo apt-get -y install docker-ce
      sudo curl -L https://github.com/docker/compose/releases/download/1.16.1/docker-compose-`uname -s`-` uname -m` -o /usr/local/bin/docker-compose
      sudo chmod +x /usr/local/bin/docker-compose
    SHELL

  end

  # vm1 - swarm master
  config.vm.define "vm1" do |vm1|
    vm1.vm.network "private_network", ip: "10.0.0.101"
    vm1.vm.hostname = "vm1"
    
    # vm1.vm.network "forwarded_port", guest: 5000, host: 5000 # crud-pedestrian port
    # vm1.vm.network "forwarded_port", guest: 5001, host: 5001 # crud-vehicle port
    # vm1.vm.network "forwarded_port", guest: 5002, host: 5002 # crud-crosswalk-location port
    # vm1.vm.network "forwarded_port", guest: 5003, host: 5003 # read-traffic-light port
    # vm1.vm.network "forwarded_port", guest: 5004, host: 5004 # crud-crosswalk-counters port
    # vm1.vm.network "forwarded_port", guest: 5005, host: 5005 # closest crosswalk port
    # vm1.vm.network "forwarded_port", guest: 5006, host: 5006 # calculate distance in crosswalk port
    # vm1.vm.network "forwarded_port", guest: 5007, host: 5007 # spws port
    # vm1.vm.network "forwarded_port", guest: 8080, host: 8080 # monitoring web service port
    # vm1.vm.network "forwarded_port", guest: 2377, host: 2377 # docker swarm management port (para que as máquinas Slaves possam juntar-se ao cluster)
    # vm1.vm.network "forwarded_port", guest: 7946, host: 7946, protocol: "udp" # for container network discovery
    # vm1.vm.network "forwarded_port", guest: 7946, host: 7946, protocol: "tcp" # for container network discovery
    # vm1.vm.network "forwarded_port", guest: 4789, host: 4789, protocol: "udp" # for the container ingress network
    
    vm1.vm.provision "shell", inline: <<-SHELL
      apt-get -y update
      apt-get -y upgrade 
      apt-get -y autoremove 
      apt-get install -y vim
      echo "#{PUBLIC_KEY}" >> /home/vagrant/.ssh/authorized_keys

      sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
      curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
      sudo apt-key fingerprint 0EBFCD88
      sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
      sudo apt-get -y update
      sudo apt-get -y install docker-ce
      sudo curl -L https://github.com/docker/compose/releases/download/1.16.1/docker-compose-`uname -s`-` uname -m` -o /usr/local/bin/docker-compose
      sudo chmod +x /usr/local/bin/docker-compose

      rm -r -f ew/
      mkdir ew/
      chmod 777 -R ew/
      echo "#{DOCKER_COMPOSE}" >> ew/docker-compose.yml
      echo "#{MASTER_SH}" >> ew/master.sh
      chmod 777 -R ew/
    SHELL

  end

  # vm4 - proxy server
  config.vm.define "vm4" do |vm4|
    vm4.vm.network "private_network", ip: "10.0.0.104"
    vm4.vm.hostname = "vm4"

    vm4.vm.provision "shell", inline: <<-SHELL
      apt-get -y update
      apt-get -y upgrade 
      apt-get -y autoremove 
      apt-get install -y vim
      echo "#{PUBLIC_KEY}" >> /home/vagrant/.ssh/authorized_keys
    SHELL

  end

end
